Plugins = ["守卫","屏蔽","开关","复读","回复","群管","订阅","查价","打乱","学习"]   #插件管理
ChannelPlugins = ["守卫","屏蔽","开关","复读","回复","订阅","查价","打乱","学习"]   #频道插件管理
Admins = [2693678434, 144115218677529987]   #机器人管理员管理
DatabaseUser = "sa"   #MSSQL数据库用户名
DatabasePassword = "wr@#kequ5060"   #MSSQL数据库密码
DatabasePort = 1433   #MSSQL数据库服务端口
DatabaseServer = "127.0.0.1"   #MSSQL数据库服务网址
ServerPort = 8081   #服务端口
ScrambleServer = "http://localhost:2014"   #打乱服务地址